{{ config(materialized='table',schema='dbo')}}
SELECT
	A_C.[CarID],
	A_S.[SaleID],
	cast(A_S.[CommDollars] as money) [CommDollars],
	cast(A_S.[StateTaxDollars] as money) [StateTaxDollars],
	cast(A_S.[StateTaxRate] as numeric(18,6)) [StateTaxRate],
	cast(A_S.[CountyTaxDollars] as money) [CountyTaxDollars],
	cast(A_S.[CountyTaxRate] as numeric(18,6)) [CountyTaxRate],
	cast(A_S.[CityTaxDollars] as money) [CityTaxDollars],
	A_S.[HoldWire] [HasHoldWire],
	cast(A_S.[CityTaxRate] as numeric(18,6)) [CityTaxRate],
	cast(A_S.[SteveCommDollars] as money) [SteveCommDollars],
	cast(A_S.[SteveCommPerc] as numeric(18,6)) [SteveCommPct],
	cast(A_S.[AsSiterCommDollars] as money) [AssiterCommDollars],
	cast(A_S.[AsSiterCommPerc] as numeric(18,6)) [AssiterCommPct],
	cast(A_S.[Price] as money) [Price],
	cast(A_S.[BuyerCommPerc] as numeric(18,6)) [BuyerCommPct],
	cast(A_S.[BuyerCommDollars] as money) [BuyerCommDollars],
	cast(A_S.[CommPerc] as numeric(18,6)) [CommPct],
	A_S.[BlockSaleID],
	cast(A_S.[ShipDateVerified] as char(1)) [ShipDateVerified],
	A_S.[CarrierID],
	cast(A_S.[Comments] as varchar(512)) [Comments],
	A_S.[BuyerCustomerAccountID] [BidderID],
	A_S.[SellerCustomerAccountID],
	A_S.[ShiptoAddressID] [ShipToAddressID],
	A_S.[ShiptoContactID] [ShipToContactID],
	cast(A_S.[Created] as datetime) [Created],
	A_S.[UpdateEventID],
	cast(A_S.[BillofLading] as char(1)) [BillOfLading],
	cast(A_S.[BillofLadingText] as varchar(100)) [BillOfLadingText],
	cast(A_S.[BMA] as varchar(255)) [BMA],
	A_S.[Legacy],
	cast(A_S.[ShipDate] as datetime) [ShipDateTime],
	cast(A_S.[Navision] as char(1)) [NAVISION],
	A_S.[BuyerdealerID] [BuyerDealerID],
	A_S.[SellerAddressID],
	A_S.[SellerDealerID],
	A_S.[AlternateSaleType],
	A_S.[SaleStatusID],
	A_S.[AuctionBidderID],
	cast(A_S.[TaxExemptCode] as varchar(4)) [TaxExemptCode],
	cast(A_S.[ArBitrated] as char(1)) [Arbitrated],
	cast(A_S.[AdjustmentReason] as nvarchar(4000)) [AdjustmentReason],
	cast(A_S.[AdjustedByUserName] as nvarchar(500)) [AdjustedByUsername],
	cast(A_S.[AdjustmentDate] as datetime) [AdjustmentDateTime],
	cast(A_S.[CarrierName] as varchar(500)) [CarrierName]
FROM [stg].[Auct_Car_FinalView] AS A_C 
JOIN [stg].[Auct_Sale_FinalView] AS A_S ON A_S.[SaleID]=.[]
