{{ config(materialized='table',schema='dbo')}}
SELECT
	A_AA.[AssignmentID],
	A_AA.[AddressID],
	A_AA.[CustomerAccountID],
	A_AA.[AddressStatusID],
	A_AA.[UpdateEventID] [UpdateEventID_AddressAssignments],
	cast(A_AA.[IsDefault] as char(1)) [IsDefault_AddressAssignments],
	cast(A_AA.[Adddescr] as varchar(8000)) [AddDescription],
	A_AA.[CompanyID] [CompanyID_AddressAssignments],
	A_AA.[AddressTypeID],
	cast(A_AT.[Icon] as nvarchar(256)) [Icon],
	cast(A_AT.[ProcessorName] as nvarchar(1024)) [ProcessorName],
	A_AT.[Level],
	A_A.[AddressID],
	cast(A_A.[Address1] as nvarchar(256)) [Address1_Address],
	cast(A_A.[Address2] as nvarchar(256)) [Address2_Address],
	cast(A_A.[City] as nvarchar(100)) [City_Address],
	cast(A_A.[StateProvince] as nvarchar(50)) [State_Address],
	cast(A_A.[PostalCode] as nvarchar(50)) [PostalCode_Address],
	A_A.[Country] [CountryID_Address],
	cast(A_A.[Created] as datetime) [Created_Address],
	A_A.[UpdateEventID] [UpdateEventID_Address],
	cast(A_A.[Careof] as varchar(100)) [CareOf],
	cast(A_A.[Active] as bit) [IsActive_Address],
	cast(A_A.[County] as nvarchar(100)) [County],
	cast(A_A.[WeBaddressID] as uniqueidentifier) [WebAddressID],
	A_C.[ContactcontactID] [ContactContactID],
	A_C.[ContactTypeID],
	A_C.[CustomerAccountID],
	cast(A_C.[ContactTitle] as varchar(64)) [ContactTitle],
	cast(A_C.[Created] as datetime) [Created_ContactContact],
	A_C.[UpdateEventID] [UpdateEventID_ContactContact],
	A_CT.[ContactTypeID],
	cast(A_CT.[Name] as varchar(500)) [ContactType],
	cast(A_CT.[Created] as datetime) [Created_ContactType],
	A_CT.[UpdateEventID] [UpdateEventID_ContactType],
	cast(A_CT.[Active] as bit) [IsActive_ContactType],
	A_C.[ContactID],
	cast(A_C.[Name] as varchar(500)) [ContactName],
	A_C.[SalutationID],
	cast(A_C.[FirstName] as varchar(500)) [FirstName],
	cast(A_C.[MiddleInitial] as varchar(500)) [MiddleInitial],
	cast(A_C.[LastName] as varchar(500)) [LastName],
	A_C.[ContactSuffixID],
	cast(A_C.[ShortNote] as varchar(8000)) [ShortNote],
	A_C.[UsersID] [UserID],
	A_C.[ContactStatusID],
	A_C.[PreferredContactMethodID],
	cast(A_C.[PreferredContactTime] as varchar(64)) [PreferredContactTime],
	A_C.[SourceID],
	cast(A_C.[DlNumber] as varchar(128)) [DLNumber],
	cast(A_C.[DlState] as varchar(128)) [DLState],
	cast(A_C.[SSN] as varchar(128)) [SSN],
	cast(A_C.[DOB] as varchar(128)) [DOB],
	cast(A_C.[PassportNumber] as varchar(128)) [PassportNumber],
	cast(A_C.[PassportCountry] as varchar(128)) [PassportCountry],
	A_C.[LegacyID],
	A_C.[IDRef],
	cast(A_C.[PartnerName] as varchar(8000)) [PartnerName],
	cast(A_C.[AccountingID] as nvarchar(100)) [AccountingID],
	cast(A_C.[VendorAccountingID] as nvarchar(100)) [VendorAccountingID],
	A_C.[CommonID],
	cast(A_C.[BCCustomerID] as uniqueidentifier) [BCCustomerID],
	cast(A_C.[BCVendorID] as uniqueidentifier) [BCVendorID],
	A_C.[CountryID],
	cast(A_C.[Name] as varchar(128)) [Country],
	A_C.[CountryCode],
	cast(A_C.[Created] as datetime) [Created_Country],
	A_C.[UpdateEventID] [UpdateEventID_Country],
	A_C.[DisplayOrder],
	cast(A_C.[SynchID] as varchar(50)) [SyncID],
	A_CA.[CustomerAccountID],
	A_CA.[ContactID],
	A_CA.[CompanyID] [CompanyID_CustomerAccount],
	A_CA.[BankAccountID],
	A_CA.[CustomerAccountStatusID],
	cast(A_CA.[Created] as datetime) [Created_CustomerAccount],
	A_CA.[UpdateEventID] [UpdateEventID_CustomerAccount],
	A_CA.[PhoneAssignmentID],
	cast(A_CA.[WebGUID] as varchar(50)) [WebGUID],
	A_CA.[ProxiBidID],
	A_CA.[OnlineUserID],
	A_E.[EmailID],
	cast(A_E.[EmailAddress] as nvarchar(320)) [Email_Emails],
	A_E.[ContactID],
	A_E.[CustomerAccountID],
	cast(A_E.[Use] as char(1)) [Use],
	cast(A_E.[Created] as datetime) [Created_Emails],
	A_E.[UpdateEventID] [UpdateEventID_Emails],
	cast(A_E.[EmailBlastOptin] as char(1)) [EmailBlastOptIn],
	cast(A_E.[EmailBlastOptinPartners] as char(1)) [EmailBlastOptInPartners],
	cast(A_E.[Active] as bit) [IsActive_Emails],
	A_PA.[PhoneAssignmentID],
	A_PA.[CustomerAccountID],
	A_PA.[PhoneID],
	A_PA.[PhoneStatusID],
	A_PA.[PhoneTypeID],
	cast(A_PA.[IsDefault] as char(1)) [IsDefault_PhoneAssignments],
	cast(A_PA.[Created] as datetime) [Created_PhoneAssignments],
	A_PA.[UpdateEventID] [UpdateEventID_PhoneAssignments],
	A_PT.[PhoneTypeID],
	cast(A_PT.[Name] as varchar(64)) [PhoneType],
	cast(A_PT.[Created] as datetime) [Created_PhoneType],
	A_PT.[UpdateEventID] [UpdateEventID_PhoneType],
	A_P.[PhoneID],
	A_P.[CountryID] [CountryID_Phone],
	cast(A_P.[AreaCode] as varchar(5)) [AreaCode],
	cast(A_P.[PhoneNumber] as nvarchar(40)) [PhoneNumber],
	cast(A_P.[Created] as datetime) [Created_Phone],
	A_P.[UpdateEventID] [UpdateEventID_Phone],
	cast(A_P.[Active] as bit) [IsActive_Phone],
	cast(A_P.[WebPhoneID] as uniqueidentifier) [WebPhoneID]
FROM [stg].[Auct_Address_FinalView] AS A_A 
JOIN [stg].[Auct_AddressAssignments_FinalView] AS A_AA ON A_AA.[AssignmentID]=.[]
JOIN [stg].[Auct_AddressTypes_FinalView] AS A_AT ON A_AT.[AddressTypeID]=.[]
JOIN [stg].[Auct_Contact_FinalView] AS A_C ON A_C.[ContactID]=.[]
JOIN [stg].[Auct_Contactcontact_FinalView] AS A_C ON A_C.[ContactcontactID]=.[]
JOIN [stg].[Auct_ContactType_FinalView] AS A_CT ON A_CT.[ContactTypeID]=.[]
JOIN [stg].[Auct_Country_FinalView] AS A_C ON A_C.[CountryID]=.[]
JOIN [stg].[Auct_CustomerAccount_FinalView] AS A_CA ON A_CA.[CustomerAccountID]=.[]
JOIN [stg].[Auct_Emails_FinalView] AS A_E ON A_E.[EmailID]=.[]
JOIN [stg].[Auct_Phone_FinalView] AS A_P ON A_P.[PhoneID]=.[]
JOIN [stg].[Auct_PhoneAssignments_FinalView] AS A_PA ON A_PA.[PhoneAssignmentID]=.[]
JOIN [stg].[Auct_PhoneType_FinalView] AS A_PT ON A_PT.[PhoneTypeID]=.[]
