{{ config(materialized='table',schema='dbo')}}
SELECT
	C_PN.[ID] [PaymentNewId],
	cast(C_PN.[CreateDate] as datetime) [Created],
	cast(C_PN.[ModifyDate] as datetime) [ModifiedDate],
	C_PN.[UserID],
	C_PN.[PaymentTypeID],
	C_PN.[CouponID],
	C_PN.[IsActive],
	C_PN.[Success] [IsSuccess],
	cast(C_PN.[OrderTotal] as money) [OrderTotalPrice],
	cast(C_PN.[OrderDiscount] as money) [OrderDiscountDollars],
	cast(C_PN.[ChargeAmount] as money) [ChargeAmountDollars],
	cast(C_PN.[CustomerInfo] as nvarchar(40)) [CardCountry],
	cast(C_PN.[PaymentInfo] as char(4)) [CardLastFour],
	cast(C_PN.[TransactionInfo] as nvarchar(20)) [PaymentStatus],
	C_P.[ID] [PaymentID],
	cast(C_P.[ZipCode] as nvarchar(50)) [PostalCode],
	cast(C_P.[Email] as nvarchar(320)) [Email],
	cast(C_P.[CustomerIP] as nvarchar(255)) [CustomerIPAddress],
	cast(C_P.[LineItemDescription] as nvarchar(4000)) [LineItemDescription],
	cast(C_P.[TransactionID] as nvarchar(50)) [TransactionID],
	cast(C_P.[FirstName] as nvarchar(500)) [FirstName],
	cast(C_P.[LastName] as nvarchar(500)) [LastName],
	cast(C_P.[Address1] as nvarchar(256)) [Address],
	cast(C_P.[City] as nvarchar(100)) [City],
	cast(C_P.[State] as nvarchar(50)) [State],
	cast(C_P.[AuthorizationCode] as nvarchar(50)) [AuthorizationCode],
	cast(C_P.[ResponseCode] as nvarchar(50)) [ResponseCode],
	cast(C_P.[ResponseReasonCode] as nvarchar(50)) [ResponseReasonCode],
	cast(C_P.[GatewayMessage] as nvarchar(4000)) [GatewayMessage],
	cast(C_P.[DiscountAmount] as money) [OrderDiscountPrice],
	cast(C_P.[ChargeAmount] as money) [ChargeAmountDollars],
	C_P.[IsActive],
	C_P.[Approved] [IsApproved],
	C_P.[ListingID],
	C_P.[PaymentTypeID],
	C_P.[CouponID],
	cast(C_P.[CreateDate] as datetime) [Created],
	cast(C_P.[ModifyDate] as datetime) [ModifiedDate]
FROM [stg].[CC_Payment_FinalView] AS C_P 
JOIN [stg].[CC_PaymentNew_FinalView] AS C_PN ON C_PN.[ID]=.[]
