{{ config(materialized='view',schema='stg')}}
Select
	[Id] [ID],
	cast([HashOrig] as nvarchar(4000)) [Hashorig],
	cast([ComputedSrcset] as nvarchar(4000)) [Computedsrcset],
	cast([UrlThumbnailWide] as nvarchar(4000)) [URLThuMbnailwIDE],
	cast([UrlSrcsetRetinaXS] as nvarchar(4000)) [URLsrcsetretinaxs],
	cast([UrlSrcsetRetinaSm] as nvarchar(4000)) [URLsrcsetretinasm],
	cast([UrlSrcsetRetinaMd] as nvarchar(4000)) [URLsrcsetretinamd],
	cast([UrlSrcsetRetinaLg] as nvarchar(4000)) [URLsrcsetretinalg],
	cast([UrlSrcsetRetinaXL] as nvarchar(4000)) [URLsrcsetretinaxl],
	cast([UrlSrcsetRetinaXXL] as nvarchar(4000)) [URLsrcsetretinaxxl],
	cast([UrlSrcsetSm] as nvarchar(4000)) [URLsrcsetsm],
	cast([UrlSrcsetMd] as nvarchar(4000)) [URLsrcsetmd],
	cast([UrlSrcsetLg] as nvarchar(4000)) [URLsrcsetlg],
	cast([UrlSrcsetXL] as nvarchar(4000)) [URLsrcsetxl],
	cast([UrlSrcsetXXL] as nvarchar(4000)) [URLsrcsetxxl],
	cast([UrlSrcsetRetinaXXS] as nvarchar(4000)) [URLsrcsetretinaxxs],
	cast([UrlCarouselCompressed] as nvarchar(4000)) [URLCarouselCompressed],
	cast([UrlJumboCompressed] as nvarchar(4000)) [URLjumboCompressed],
	cast([UrlThumbnailCompressed] as nvarchar(4000)) [URLThuMbnailCompressed],
	cast([UrlStandardCompressed] as nvarchar(4000)) [URLstandardCompressed],
	cast([UrlSrcsetXXS] as nvarchar(4000)) [URLsrcsetxxs],
	cast([UrlSrcsetXS] as nvarchar(4000)) [URLsrcsetxs],
	cast([UrlOrig] as nvarchar(4000)) [URLorig],
	cast([UrlStandard] as nvarchar(4000)) [URLstandard],
	cast([UrlThumbnail] as nvarchar(4000)) [URLThuMbnail],
	cast([UrlJumbo] as nvarchar(4000)) [URLjumbo],
	cast([FullUrl] as nvarchar(4000)) [FullURL],
	cast([UrlCarousel] as nvarchar(4000)) [URLCarousel],
	[ListingId] [ListingID],
	[ListingImageTypeId] [ListingImageTypeID],
	[Sequence] [Sequence],
	[CreateDate] [CreateDate],
	[ModifyDate] [ModifyDate],
	[IsActive] [IsActive],
	[Letterbox] [LetterBox],
	[UseCompressedImages] [UseCompressedImages],
	[SrcsetComputed] [SrcsetComputed]
From stg.[CC_ListingImage_Raw]
