{{ config(materialized='view',schema='stg')}}
Select
	[Id] [ID],
	cast([ZipCode] as nvarchar(4000)) [ZipCode],
	cast([Email] as nvarchar(4000)) [Email],
	cast([Telephone] as nvarchar(4000)) [TelePhone],
	cast([CustomerIp] as nvarchar(4000)) [CustomerIP],
	cast([LineItemDescription] as nvarchar(4000)) [LineItemDescription],
	cast([TransactionId] as nvarchar(4000)) [TransactionID],
	cast([FirstName] as nvarchar(4000)) [FirstName],
	cast([LastName] as nvarchar(4000)) [LastName],
	cast([Address1] as nvarchar(4000)) [Address1],
	cast([Address2] as nvarchar(4000)) [Address2],
	cast([City] as nvarchar(4000)) [City],
	cast([State] as nvarchar(4000)) [State],
	cast([AuthorizationCode] as nvarchar(4000)) [AuthorizationCode],
	cast([ResponseCode] as nvarchar(4000)) [ResponseCode],
	cast([ResponseReasonCode] as nvarchar(4000)) [ResponseReasonCode],
	cast([GatewayMessage] as nvarchar(4000)) [GatewayMessage],
	[DiscountAmount] [DiscountAmount],
	[ChargeAmount] [ChargeAmount],
	[IsActive] [IsActive],
	[Approved] [Approved],
	[ListingId] [ListingID],
	[PaymentTypeId] [PaymentTypeID],
	[CouponId] [CouponID],
	[CreateDate] [CreateDate],
	[ModifyDate] [ModifyDate]
From stg.[CC_Payment_Raw]
