{{ config(materialized='view',schema='stg')}}
Select
	[Id] [ID],
	cast([State] as nvarchar(4000)) [State],
	cast([ZipCode] as nvarchar(4000)) [ZipCode],
	cast([SearchDescription] as nvarchar(4000)) [SearchDescription],
	cast([DML_Operation] as nvarchar(4000)) [Dml_Operation],
	cast([SavedSearchName] as nvarchar(4000)) [SavedSearchName],
	cast([Make] as nvarchar(4000)) [Make],
	cast([Model] as nvarchar(4000)) [Model],
	cast([Country] as nvarchar(4000)) [Country],
	[PriceFrom] [PriceFrom],
	[PriceTo] [Priceto],
	[IsActive] [IsActive],
	[IncludePrivate] [IncludePrivate],
	[IncludeDealer] [IncludeDealer],
	[IncludeAuction] [IncludeAuction],
	[UserId] [UserID],
	[YearFrom] [YearFrom],
	[YearTo] [Yearto],
	[Distance] [Distance],
	[VehicleTypeId] [VehicleTypeID],
	[AlertModeId] [AlertModeID],
	[AlertFrequencyId] [AlertFrequencyID],
	[SavedSearchAuditPK] [SavedSearchAuditPK],
	[AuditEntryDateUTC] [AuditentryDateUTC],
	[CreateDate] [CreateDate],
	[ModifyDate] [ModifyDate]
From stg.[CC_SavedSearchesAudit_Raw]
